apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: playbook-dispatcher-api
  namespace: default
spec:
 template:
  metadata:
    labels:
      rhproject: hackathon2021
  spec:
    containerConcurrency: 2
    containers:
    - image: quay.io/jharting/playbook-dispatcher@sha256:5003db1eebfe2eaa7ba62253f8e152d5dbb130e4de1ecfa1f1f9332b6d247c74
      args:
      - run
      - -m
      - api
      env:
        - name: LOG_LEVEL
          value: debug
        - name: DEMO_MODE
          value: "true"
        - name: PSK_AUTH_TEST
          value: xwKhCUzgJ8
        - name: CLOWDER_ENABLED
          value: "false"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db.host
              name: playbook-dispatcher-db
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: db.port
              name: playbook-dispatcher-db
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db.name
              name: playbook-dispatcher-db
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db.user
              name: playbook-dispatcher-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: playbook-dispatcher-db

      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /live
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /ready
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
