apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: playbook-dispatcher-validator
  namespace: default
spec:
 template:
  metadata:
    labels:
      rhproject: hackathon2021
  spec:
    containerConcurrency: 2
    containers:
    - image: quay.io/jharting/playbook-dispatcher@sha256:5003db1eebfe2eaa7ba62253f8e152d5dbb130e4de1ecfa1f1f9332b6d247c74
      args:
      - run
      - -m
      - validator
      env:
        - name: LOG_LEVEL
          value: debug
        - name: CLOWDER_ENABLED
          value: "false"

      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /live
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /ready
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5

---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: response-consumer
  bootstrapServers:
  - default-kafka.default.svc.cluster.local:29092
  topics:
  - platform.upload.playbook-default-default
  sink:
    uri: http://broker-ingress.knative-eventing.svc.cluster.local/default/default

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    eventing.knative.dev/broker: default
  name: playbook-dispatcher-validator
spec:
  broker: default
  filter:
    attributes:
      source: /apis/v1/namespaces/default/kafkasources/kafka-source#platform.upload.playbook-default-default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: playbook-dispatcher-validator
      namespace: default
